### ISSUE TITLE
Simple Calendar 3.1.36 has PHP 8.2.0 Fatal Error

### ISSUE THREAD

**Issue by gregarios** [Xtendify/Simple-Calendar#355]
Using WordPress 6.1.1
Simple Calendar 3.1.36 has PHP 8.2.0 Fatal Error:

```
[Mon Dec 12 06:05:11.902044 2022] [fcgid:warn] mod_fcgid: stderr: PHP Fatal error:  Uncaught TypeError: SimpleCalendar\\plugin_deps\\Carbon\\Carbon::setLastErrors(): Argument #1 ($lastErrors) must be of type array, bool given, called in /wp-content/plugins/google-calendar-events/third-party/nesbot/carbon/src/Carbon/Traits/Creator.php on line 81 and defined in /wp-content/plugins/google-calendar-events/third-party/nesbot/carbon/src/Carbon/Traits/Creator.php:674
[Mon Dec 12 06:05:11.902111 2022] [fcgid:warn] mod_fcgid: stderr: Stack trace:
[Mon Dec 12 06:05:11.902117 2022] [fcgid:warn] mod_fcgid: stderr: #0 /wp-content/plugins/google-calendar-events/third-party/nesbot/carbon/src/Carbon/Traits/Creator.php(81): SimpleCalendar\\plugin_deps\\Carbon\\Carbon::setLastErrors()
[Mon Dec 12 06:05:11.902122 2022] [fcgid:warn] mod_fcgid: stderr: #1 /wp-content/plugins/google-calendar-events/third-party/nesbot/carbon/src/Carbon/Traits/Creator.php(212): SimpleCalendar\\plugin_deps\\Carbon\\Carbon->__construct()
[Mon Dec 12 06:05:11.902138 2022] [fcgid:warn] mod_fcgid: stderr: #2 /wp-content/plugins/google-calendar-events/includes/functions/shared.php(241): SimpleCalendar\\plugin_deps\\Carbon\\Carbon::now()
[Mon Dec 12 06:05:11.902143 2022] [fcgid:warn] mod_fcgid: stderr: #3 /wp-content/plugins/google-calendar-events/includes/functions/shared.php(166): simcal_get_calendar_names_i18n()
[Mon Dec 12 06:05:11.902147 2022] [fcgid:warn] mod_fcgid: stderr: #4 /wp-content/plugins/google-calendar-events/includes/calendars/views/default-calendar-grid.php(143): simcal_common_scripts_variables()
[Mon Dec 12 06:05:11.902152 2022] [fcgid:warn] mod_fcgid: stderr: #5 /wp-content/plugins/google-calendar-events/includes/assets.php(126): SimpleCalendar\\Calendars\\Views\\Default_Calendar_Grid->scripts()
[Mon Dec 12 06:05:11.902156 2022] [fcgid:warn] mod_fcgid: stderr: #6 /wp-includes/class-wp-hook.php(308): SimpleCalendar\\Assets->load()
[Mon Dec 12 06:05:11.902160 2022] [fcgid:warn] mod_fcgid: stderr: #7 /wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
[Mon Dec 12 06:05:11.902164 2022] [fcgid:warn] mod_fcgid: stderr: #8 /wp-includes/plugin.php(517): WP_Hook->do_action()
[Mon Dec 12 06:05:11.902168 2022] [fcgid:warn] mod_fcgid: stderr: #9 /wp-includes/script-loader.php(2180): do_action()
[Mon Dec 12 06:05:11.902172 2022] [fcgid:warn] mod_fcgid: stderr: #10 /wp-includes/class-wp-hook.php(308): wp_enqueue_scripts()
[Mon Dec 12 06:05:11.902177 2022] [fcgid:warn] mod_fcgid: stderr: #11 /wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
[Mon Dec 12 06:05:11.902181 2022] [fcgid:warn] mod_fcgid: stderr: #12 /wp-includes/plugin.php(517): WP_Hook->do_action()
[Mon Dec 12 06:05:11.902185 2022] [fcgid:warn] mod_fcgid: stderr: #13 /wp-includes/general-template.php(3043): do_action()
[Mon Dec 12 06:05:11.902189 2022] [fcgid:warn] mod_fcgid: stderr: #14 /wp-content/themes/wshg/header.php(20): wp_head()
[Mon Dec 12 06:05:11.902193 2022] [fcgid:warn] mod_fcgid: stderr: #15 /wp-includes/template.php(783): require_once('...')
[Mon Dec 12 06:05:11.902197 2022] [fcgid:warn] mod_fcgid: stderr: #16 /wp-includes/template.php(718): load_template()
[Mon Dec 12 06:05:11.902202 2022] [fcgid:warn] mod_fcgid: stderr: #17 /wp-includes/general-template.php(48): locate_template()
[Mon Dec 12 06:05:11.902206 2022] [fcgid:warn] mod_fcgid: stderr: #18 /wp-content/themes/wshg/index.php(13): get_header()
[Mon Dec 12 06:05:11.902211 2022] [fcgid:warn] mod_fcgid: stderr: #19 /wp-includes/template-loader.php(106): include('...')
[Mon Dec 12 06:05:11.902246 2022] [fcgid:warn] mod_fcgid: stderr: #20 /wp-blog-header.php(19): require_once('...')
[Mon Dec 12 06:05:11.902250 2022] [fcgid:warn] mod_fcgid: stderr: #21 /index.php(17): require('...')
[Mon Dec 12 06:05:11.902254 2022] [fcgid:warn] mod_fcgid: stderr: #22 {main}
[Mon Dec 12 06:05:11.902258 2022] [fcgid:warn] mod_fcgid: stderr:   thrown in /wp-content/plugins/google-calendar-events/third-party/nesbot/carbon/src/Carbon/Traits/Creator.php on line 674
```

**Comment by gregarios** [comment]
Here is the fix. Maybe someone can verify it or integrate the newest third party "Carbon" plugin for a better fix but this is the quick and dirty fix to get it working:

In this file:
/wp-content/plugins/google-calendar-events/third-party/nesbot/carbon/src/Carbon/Traits/Creator.php

Replace the `private static function setLastErrors($lastErrors)` starting on line number 667 with this code:

```
 /**
     * Set last errors.
     *
     * @param array|bool $lastErrors
     *
     * @return void
     */
    private static function setLastErrors($lastErrors)
    {
        if (\is_array($lastErrors) || $lastErrors === false) {
            static::$lastErrors = \is_array($lastErrors) ? $lastErrors : [
                'warning_count' => 0,
                'warnings' => [],
                'error_count' => 0,
                'errors' => [],
            ];
        }
    }
```
Please integrate this.

**Comment by rosinghal** [comment]
Thanks, @gregarios 
Awesome job in handling this. We will see if the library has an update for PHP 8.2 and update it in the plugin.

**Comment by gregarios** [comment]
> Thanks, @gregarios Awesome job in handling this. We will see if the library has an update for PHP 8.2 and update it in the plugin.

Thank you. In fact my code snippet is taken from the newest version of the library.

**Comment by rosinghal** [comment]
@gregarios @ericjsilva we have made a pre-release, can you download and check if https://github.com/Xtendify/Simple-Calendar/releases/download/3.1.37.2/simple-calendar-3.1.37.2.zip works correctly for you?

**Comment by rosinghal** [comment]
Thanks for the feedback @gregarios. Can you please let me know your WordPress and PHP version?
I will check for some more users to see, if all good then we can release.

**Comment by gregarios** [comment]
> Thanks for the feedback @gregarios. Can you please let me know your WordPress and PHP version? I will check for some more users to see, if all good then we can release.

WordPress 6.1.1 and PHP 8.2.1

**Comment by rosinghal** [comment]
Closing this since latest release works well

**Comment by gregarios** [comment]
> 

I assume the public release of this is forthcoming then? :-)

**Comment by rosinghal** [comment]
That's correct. @gregarios
